name: Build TGHMod

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Build ScriptHook
        run: |
          msbuild ScriptHook.sln /t:ScriptHook /p:Configuration=Release /p:Platform=Win32

      - name: Build TGHMod
        shell: cmd
        run: |
          cl /nologo /LD /EHsc /O2 /MT TGHMod.cpp /I ScriptHook /link Release\ScriptHook.lib /OUT:TGHMod.dll

      - name: Make ASI
        shell: cmd
        run: |
          copy /Y TGHMod.dll TGHMod.asi

      - name: Prepare Runtime Files
        shell: cmd
        run: |
          mkdir Runtime
          copy /Y Release\ScriptHook.dll Runtime\ScriptHook.dll
          copy /Y TGHMod.asi Runtime\TGHMod.asi

      - name: Upload TGHMod
        uses: actions/upload-artifact@v4
        with:
          name: TGHMod-Complete
          path: Runtime
