name: Build TGHMod
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86

      - name: Download Full SDK
        run: |
          git clone https://github.com/FoulPlay/GTAIVScriptHook_0.4.0_SDK.git SDK

      - name: Compile SDK to get lib
        run: |
          cd SDK
          msbuild ScriptHook.sln /p:Configuration=Release /p:Platform=Win32
          cd ..

      - name: Compile TGHMod
        run: |
          cl /LD /EHsc /O2 /MT /I. /IScriptHook TGHMod.cpp /link SDK\Release\ScriptHook.lib /OUT:TGHMod.dll

      - name: Make ASI
        run: copy /Y TGHMod.dll TGHMod.asi

      - name: Upload ASI
        uses: actions/upload-artifact@v4
        with:
          name: TGHMod-ASI
          path: TGHMod.asi
